[package]
name = "j-is-d-boss"
version = "0.1.0"
authors = ["jespinhara <j@jspin.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
hexdump = "0.1.0"